### ISSUE TITLE
The description of V2T, V2E, E0E?

### ISSUE THREAD

**Issue by yoczhang** [FESTUNG/project#1]
Dear all,
  I read the generateGridData.m but the description of V2T, V2E, E0E missing?

**Comment by reuterbal** [comment]
Dear @yoczhang,
thank you for your question! 

V2T is a matrix of size #V x 3 providing global vertex indices of triangles while accounting for the counter-clockwise ordering.

V2E is a symmetric sparse matrix (#V x #V) in which each row corresponds to a vertex, holding the ids of all adjacent edges. A non-zero entry at position (i,j) means, that vertices i and j are connected via an edge, and the value at this position gives the id of the edge.

E2E is a matrix of size #E x 2 providing for each edge its local index (1, 2, 3) in the adjacent triangle. A value of zero indicates a boundary edge.

The documentation of the file was updated accordingly in 480d1c82820fb0e536ef0ad34bbde354c113aa44.

Hope that helps!
Balthasar
